# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nicoly Monteiro
tagline:          'My teaching portfolio'
description:      "Hi! I'm a Romance Studies PhD student at Duke."
url:              http://nicolymonteiro.github.io
baseurl:          ""

author:
  name:           'Nicoly Monteiro dos Santos'
  url:            https://twitter.com/nicoly_mds

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
